# Generated by Django 5.0.1 on 2024-03-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('phone_Number', models.CharField(max_length=200)),
                ('MemberShip', models.CharField(max_length=200)),
            ],
        ),
    ]
