# Generated by Django 5.0.1 on 2024-03-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='MemberShip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_Number',
        ),
    ]
