# Generated by Django 5.0.1 on 2024-03-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_remove_user_email_remove_user_membership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Email',
            field=models.EmailField(default='SOME STRING', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='Gender',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='Username',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_Number',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
