# Generated by Django 5.0.1 on 2024-03-24 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_user_date_of_birth_user_email_user_gender_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
    ]
