# Generated by Django 5.0.1 on 2024-03-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
