# Generated by Django 5.0.1 on 2024-03-27 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_pub',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='Location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='Phone_Number',
            field=models.CharField(default='', max_length=200),
        ),
    ]
