# Generated by Django 5.0.1 on 2024-03-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_product_product_pub_alter_product_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_Price',
            field=models.CharField(max_length=200),
        ),
    ]
