# Generated by Django 5.0.1 on 2024-03-27 17:29

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_alter_product_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='images', validators=[apps.models.validate_image_width]),
        ),
    ]
