# Generated by Django 5.0.1 on 2024-03-31 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_alter_product_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer',
        ),
    ]
