# Generated by Django 5.0.1 on 2024-04-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='', upload_to='profile'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
