# Generated by Django 5.0.1 on 2024-04-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_customer_image_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(default='', upload_to='cart'),
        ),
    ]
