# Generated by Django 5.0.1 on 2024-04-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_cart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Phone_Number',
            field=models.CharField(default='', max_length=200),
        ),
    ]
